### ISSUE TITLE
Figure out how to keep a consistent Mistletoe AST before the docutils render

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#58]
In https://github.com/ExecutableBookProject/MyST-Parser/issues/113 we realized that there would be some unexpected behavior as a result of parsing each cell as a separate "document". e.g., footnote definitions would not be collected across multiple cells.

We should figure out how to get around this

@mmcky mentioned this would be particularly problematic for him!

**Comment by mmcky** [comment]
thanks for raising this issue @choldgraf. I think this is mainly a problem for the use case of supporting books in general. I think `footnotes` will need to be collected and resolved across cells as it is reasonable to expect a file to represent chapters / sections etc. 

How do we resolve `references` across notebooks (at the project level)?  I guess the issue here is that `references` such as `bibtex` is global across `notebooks` while footnotes are a local definition within each `notebook`?

**Comment by chrisjsewell** [comment]
With the shiny new `mistletoe-ebp` API (see https://mistletoe-ebp.readthedocs.io/en/latest/using/intro.html#programmatic-use), I think there could be a better way to parse the notebook, more inline with how it will occur for the text based representation, along the lines of:

1. Convert the full notebook to the 'intermediate' mistletoe/markdown AST (before inline text is processed)
2. Walking this AST to 'expand' `SpanContainer` (see https://mistletoe-ebp.readthedocs.io/en/latest/using/intro.html#the-parse-process)
2. Applying the `SphinxRenderer` once on the full AST (rather than for each cell as is done now).

This would involve creating a specific `CodeCell` mistletoe token, then adding an extra render method to `SphinxRenderer` that knows how to deal with it, basically using the code from https://github.com/ExecutableBookProject/MyST-NB/blob/d089de3c1140f72daf7c579be7637164ee548028/myst_nb/parser.py#L98

This logic could be problematic: https://github.com/ExecutableBookProject/MyST-NB/blob/d089de3c1140f72daf7c579be7637164ee548028/myst_nb/parser.py#L89

As we have already discussed in #30

Ideally we would also need to work out a way to incorporate #21. A first step to achieving this would be  ExecutableBookProject/mistletoe-ebp#9
